chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('checkForRoom/', views.checkForRoom, name='checkForRoom'),
    path('<str:room>/', views.room, name='room'),
    path('', views.home, name='home'),
    path('send', views.send, name='send'),
    path('get/<str:room>/', views.get, name='get'),
]

fisbook/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls')),
    path('users/',include('users.urls')),
    path('',include('forums.urls')),
    path('chat/', include('chat.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forums/urls.py
from django.urls import path,include
from . import views

app_name='forums'

urlpatterns = [
    path('forums/<str:forum_id>',views.forum,name='forum'),
    path('event/<int:event_id>',views.event,name='event'),
    path('forums/<int:forum_id>/members',views.member_list,name='member_list'),
    path('test', views.test, name='test')
]


pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('',views.home,name='home'),
    path('explore/',views.explore,name='explore'),
    path('user/<slug:reg_no>',views.user,name='user'),
    path('explore/get/<str:forum>', views.get, name='get')
]

users/urls.py
from django.urls import path,include

app_name = 'users'


urlpatterns = [
    path('',include('django.contrib.auth.urls'))
]

forums/models.py
from django.db import models
from users.models import CustomUser

# Create your models here.

class Forum(models.Model):
    def __str__(self):
        return (f"{self.name}  #{str(self.id)}" )
    name = models.CharField(max_length=150)
    about = models.TextField()
    users = models.ManyToManyField(CustomUser,related_name='forums')
    mods = models.ManyToManyField(CustomUser,related_name='mod_forums')
    is_public = models.BooleanField(default=False)
    pic = models.ImageField(upload_to='forums', default='media/forums/Dragonfruit2.jpg')
    
    
    

class Events(models.Model):
    def __str__(self):
        return(f"{self.title}  #{str(self.id)}")
    forum = models.ManyToManyField(Forum,related_name='events',blank=True)
    title = models.CharField(max_length=150)
    about = models.TextField()
    date = models.DateTimeField()
    is_public = models.BooleanField(default=False)
    users_added = models.ManyToManyField(CustomUser,blank=True,related_name='events_added')

    
class Notices(models.Model):
    def __str__(self):
        return(f"{self.title}  #{str(self.id)}")
    forum = models.ManyToManyField(Forum,related_name='notices')
    title = models.CharField(max_length=150)
    about = models.TextField()
    
    
class JoinReq(models.Model):
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,PermissionsMixin
from .managers import CustomUserManager

# Create your models here.


class CustomUser(AbstractBaseUser,PermissionsMixin):
    reg_no = models.CharField(max_length=20,primary_key=True,unique=True)
    first_name = models.CharField(max_length=150)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False) 
    USERNAME_FIELD = 'reg_no'
    REQUIRED_FIELDS=['first_name']
    objects = CustomUserManager()
    pic = models.ImageField(upload_to='profiles', default='/Dragonfruit.jpg')

forums/forms.py
from .models import Events
from django import forms

class ScheduleForm(forms.ModelForm):
    class Meta():
        model = Events
        fields = ['forum', 'title', 'about', 'date', 'is_public', 'users_added']

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (model.USERNAME_FIELD,'first_name',)
        

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (model.USERNAME_FIELD,'first_name',)
        



forums/views.py
from django.shortcuts import render, redirect
from .models import Forum,Events,Notices,JoinReq
from chat.models import Room
from django.utils import timezone
from django.db.models import Q
from django.http import HttpResponse
from .forms import ScheduleForm
from users.models import CustomUser
# Create your views here.

def forum(request,forum_id):
    forum = Forum.objects.get(id=forum_id)
    members = forum.users.all()
    if request.user in members:
        if request.method == 'POST':
            if "chat" in request.POST:
                room = Forum.objects.get(id=forum_id)
                roomName = room.name
                user = request.user.first_name
                if Room.objects.filter(name=roomName).exists():
                    return redirect('/chat/' + roomName + '/?user=' + user)
                else:
                    newRoom = Room.objects.create(name=roomName)
                    newRoom.save()
                    return redirect('/chat/' + roomName + '/?user=' + user)
            else:
                form = ScheduleForm(request.POST)
                if form.is_valid():
                    event = form.save()
                    event1 = Events.objects.get(id=event.id)
                    event1.users_added.add(request.user)
                    return redirect('/forums/'+forum_id)
                else:
                    return HttpResponse(f'Form error: {form.errors}')
        else:
            events = Events.objects.filter(forum__id = forum_id).order_by('date').filter(Q(date__gte=timezone.now()))
            notices = Notices.objects.filter(forum__id=forum_id)
            form = ScheduleForm()
            context = {'forum':forum,'events':events,'notices':notices,'form':form,'members':members}
            return render(request,'forum.html',context)
    else:
        member = CustomUser.objects.get(reg_no=request.user)
        forum = Forum.objects.get(id=forum_id)
        if request.method == "POST":
            if "request" in request.POST:
                req = JoinReq.objects.filter(forum=forum,user=member)
                if not req:
                    JoinReq.objects.create(forum=forum,user=member)
        req = JoinReq.objects.filter(forum=forum,user=member)
        context = {'req':req}
        return render(request,'request.html',context)
        
        

def test(request):
    return render(request, 'test.html')

def event(request,event_id):
    if request.method=='POST':
            room = Events.objects.get(id=event_id)
            roomName = room.title
            user = request.user.first_name
            if Room.objects.filter(name=roomName).exists():
                return redirect('/chat/' + roomName + '/?user=' + user)
            else:
                newRoom = Room.objects.create(name=roomName)
                newRoom.save()
                return redirect('/chat/' + roomName + '/?user=' + user)
    else:    
        event = Events.objects.get(id=event_id)
        context = {'event':event,'forum':forum}
        return render(request,'event.html',context)

'''
def member_list(request,forum_id):
    forum = Forum.objects.get(id=forum_id)
    user_forums = request.user.forums.all()
    if forum.is_public or forum in user_forums:
        members = forum.users.all()
        mods = forum.mods.all()
        context = {'members':members,'mods':mods}
        return render(request,'members.html',context)
    else:
        valid = False
        context = {'valid':valid}
        return render(request,'invalid.html',context)
''' 
       
''' if request.method == 'POST':
        if request.POST.get('chat')==True:
            room = Forum.objects.get(id=forum_id)
            roomName = room.name
            user = request.user.first_name
            if Room.objects.filter(name=roomName).exists():
                return redirect('/chat/' + roomName + '/?user=' + user)
            else:
                newRoom = Room.objects.create(name=roomName)
                newRoom.save()
                return redirect('/chat/' + roomName + '/?user=' + user)
        else:
            form = ScheduleForm(request.POST)
            if form.is_valid():
                form.save()
                return HttpResponse('success')'''
                

def member_list(request,forum_id):
    forum = Forum.objects.get(id=forum_id)
    if request.user in forum.mods.all():
        if request.method == 'POST' :
            if 'accept' in request.POST:
                member = CustomUser.objects.get(reg_no=request.POST['accept'])
                forum.users.add(member)
                JoinReq.objects.filter(forum=forum,user=member).delete()
            elif 'remove' in request.POST:
                member = CustomUser.objects.get(reg_no=request.POST['remove'])
                forum.users.remove(member)
            elif 'makemod' in request.POST:
                member = CustomUser.objects.get(reg_no=request.POST['makemod'])
                forum.mods.add(member)
            elif 'removemod' in request.POST:
                member = CustomUser.objects.get(reg_no=request.POST['removemod'])
                forum.mods.remove(member)               
        else:
            pass
        mods = forum.mods.all()
        members = forum.users.all()
        join_reqs = JoinReq.objects.filter(forum = forum)
        context = {'join_reqs':join_reqs,'members':members,'mods':mods}
        return render(request,'members.html',context)
    else:
        return render(request,'invalid.html')

users/views.py
from django.shortcuts import render

# Create your views here.

templates/_base.html
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}FIS-book{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    
    <style>
        .nav-link:hover{
            text-decoration:underline
        }
        body{
            background-color: #f8e9a1
        }
        nav{
            background-color: #daad86
        }
        .carouselText{
            color:white;
        }


    </style>
</head>
<body>
    <nav class = 'navbar navbar-expand-lg'>
        <ul class = 'navbar-nav mr-auto'>
            <h2>Navigate: </h4> &nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp
            <h4><li><a class = 'nav-link' href = "{% url 'pages:home' %}">Homepage</a></h4>
                <h4><li><a class = 'nav-link' href = "{% url 'pages:user' request.user %}">Profile</a></h4>
                    <h4><li><a class = 'nav-link' href = "{% url 'pages:explore' %}">Explore</a></h4>
            <h4><li><a class = 'nav-link' href="{% url 'users:logout' %}">Log out</a></li></h4>
        </ul>
    </nav>
    <div class="container">
       
        {% block content %}
        {% endblock content %}
    </div>

    </div>
    <script>
        $(document).ready(function() {
          $('.carousel').carousel();
        });
      </script>
</body>
</html>

templates/event.html

<html>
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

        <style>
            body{
                background-color: #f8e9a1
            }
        </style>

    </head>
    <body>
        <div class = 'container p-5 my-5 bg-dark text-light'>
            <h1>{{event.title}}</h1>

            <h3>{{event.date}}</h3>
            <br>
    
            <h2>{{event.about}}</h2>

            <form method = 'POST' type = 'hidden' id = 'postForm'>
                {% csrf_token %}
                <button type = 'submit' class = 'btn btn-success btn-lg'>Chat</button>
            </form>  

             
        </div>

        <div class = 'container p-5 my-5 bg-dark text-light'>
            <h1><u>People: </u></h1> <br>

            {% for object in event.users_added.all %}
                <h2> {{object.first_name}} </h2>
            {% endfor %} 

             
        </div>

    </body>
</html>


templates/explore.html

{% extends '_base.html' %}

<html>
    <head>
        <title>Explore</title>
        
    </head>
    <body>
        {% block content %}
        <div class = 'container p-5 my-5 bg-dark text-light'>
            <h1>Public Forums:</h1>
        </div>

        <input class = "searchBar" style = "width:50%; height:7%; font-size:xx-large" placeholder = 'Search'> <br>
        <div id = 'results' class = 'container p-5 my-5 bg-dark text-light'>
          <h1>Results:</h1><br>
        </div>
      

        <br>

        <h1>Public Events:</h1>
        {% for event in events %}
            <a href="{% url 'forums:event' event.id %}">{{event.title}}</a>
        {% endfor %}

        <script>
          function getForums() {
            var forum = $(".searchBar").val();
            console.log(forum)
            
            $.ajax({
                type: 'GET',
                url: '/explore/get/' + forum,
                success: function(response) {
                    var forums = response.forums;
                    console.log(forums)
                    var resultContainer = $("#results");
                    resultContainer.empty();
        
                    for (let i = 0; i < forums.length; i++) {
                        var forum = forums[i];
                        var forumHtml = '<h3>'+forum.name+'</h3>'
                        resultContainer.append(forumHtml)
                        var buttonElement = $('<button/>', {
                          text:'Go To Forum',
                          class:'btn btn-lg btn-success',
                          click: function(){
                            window.location.href = '/forums/'+forum.id
                          }
                        })
                        resultContainer.append(buttonElement)
                    }
                }
            });
        }

        setInterval(getForums, 2000)
        </script>
        {% endblock %}
    </body>
</html>

templates/forum.html


<html>
    <head>
        <title>{{forum.name}}</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
        <style>
            body{
                background-color: #f8e9a1
            }
            h3{
                
                font-family:'Courier New', Courier, monospace;
                font-weight:bold;
            }
            .nav-link:hover{
                text-decoration:underline
            }
           
            nav{
                background-color: #daad86
            }
            .carouselText{
                color:white;
            }
            .card{
                background-color:#daad86
            }
            .cardContainer{
                background-color:#f8e9a1
            }
            li{
                border-radius:10px;
            }
            .row{
                overflow-x:auto;
                max-width: 100%;
            }
            button{
                background-color: #45a29e;
                width: 300px;
                height: 70px;
                font-weight: bold;
                font-size: 200%;
                border-radius: 50px;
                color:#0b0c10;
                position:relative;
                font-family: courier;
              }
              
             
              
        </style>

    </head>
    <body>
       

        
        
        <div class = 'container p-5 my-3 bg-dark text-light'>
            <h1><center> {{forum.name}} </center></h1>
        </div>
        <div class = 'container p-5 my-2 bg-secondary text-dark'>
            <h3>{{forum.about}}</h3>
            
        <form method = 'POST' type = 'hidden' id = 'postForm'>
            {% csrf_token %}
            <input type = 'hidden' id = 'roomName' value = {{forum.name}}>
            <input type = 'hidden' id= 'id' value = {{forum.id}}>
            <button type = 'submit' class = 'btn btn-success btn-lg' name = "chat">Chat</button>
        </form>      
    
            
            
        </div>
        
        <br>
        <div class = 'container my-4 p-4 bg-dark text-light'>
            <h2>Events</h2>
        </div>
        <div class = 'row'>
            {% for event in events %}
            <div class = 'col'>
              <div class = 'card w-5 mb-3'>
                <div class = 'card-header bg-dark text-light'>
                  {{event.date}}
                </div>
                <div class = 'card-body bg-secondary text-light'>
                  <div class = 'card-title'>
                    <h2> {{event.title}} </h2>
                  </div>
                  <div class = 'container p-3 my-2 bg-dark text-light'><h5>{{event.about}}</h5></div>
          
                  
                  <br>
                  <center><a class = 'btn btn-dark' href = "{% url 'forums:event' event.id %}">Go To Event</a></center>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>

        <div class = 'container my-4 p-4 bg-dark text-light'>
            <h1>Schedule an Event</h1> <br>
            <p>*Enter date in yyyy-mm-dd format <br> Hold shift and drag to select consecutive choices <br> Hold control and click to select non-consecutive choices</p>
            <form method = 'POST'>
                {% csrf_token %}
                <h3>Forum</h3> 
                <div id = "forumList"> {{form.forum}}<br></div>
                <h3>Title</h3>
                {{form.title}}<br>
                <h3>About</h3>
                {{form.about}}<br>
                <h3>Date</h3>
                {{form.date}}<br>
                <h3>Is Public</h3>
                {{form.is_public}}<br>
                
                <br><br>
                
                <button type = 'submit' class = 'btn btn-primary btn-lg'> Schedule </button>
            </form>
        </div>
        <div class = 'container my-4 p-4 bg-dark text-light'>
            <h2>Notices</h2>
        </div>
        {% for notice in notices %}
            <p>{{notice.title}}</p>
        {% empty %}
            <p class = 'text-dark'>Nothing here yet</p>
        {% endfor %}

    </body>

</html>



templates/home.html
{% extends '_base.html' %}
{% load static %}
{% block content %}

<div class = 'container p-5 my-3 bg-dark text-light'>
<h1><center>Homepage</center></h1>
</div>


    <div id="carouselExample" class="carousel slide">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="/media/forumPic.jpeg" class="d-block w-100" alt="..." height='500'>
          
        </div>
        {% for forum in forums %}
        <div class="carousel-item">
          <a href="{% url 'forums:forum' forum.id %}"><img src='{{ forum.pic.url }}' class="d-block w-100" alt="..." height='500'></a>
          <div class = 'carousel-caption bg-dark text-light'>
            <h2 class = 'carouselText'>{{forum.name}}</h2>
          </div>
        </div>
        {% endfor %}
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>



<br>
<div class = 'cardContainer'>
<div class = 'container my-4 p-4 bg-dark text-light'>
<h2>Events You're In </h2>
</div>
<div class = 'row'>
{% for event in users_events %}
  <div class = 'col'>
    <div class = 'card w-5 mb-3'>
      <div class = 'card-header bg-dark text-light'>
        {{event.date}}
      </div>
      <div class = 'card-body bg-secondary text-light'>
        <div class = 'card-title'>
          <h2> {{event.title}} </h2>
        </div>
        <div class = 'container p-3 my-2 bg-dark text-light'><h5>{{event.about}}</h5></div>

        
        <br>
        <center><a class = 'btn btn-dark' href = '{% url 'forums:event' event.id %}'>Go To Event</a></center>
      </div>
    </div>
  </div>
{% endfor %}
</div>
</div>
<br>
<div class = 'container my-4 p-4 bg-dark text-light'>
  <h2>Other Upcoming Events</h2>
  </div>
{% for event in events %}
    {% if event not in users_events %}
        <a href="{% url 'forums:event' event.id %}">{{event.title}}<br>{{event.date}}</a>
    {% endif %}
{% endfor %}

{% endblock content %}

templates/members.html
REQUESTS:
<br>
{% for join_req in join_reqs %}
<form method="POST">
    {% csrf_token %}
    {{join_req.user}}
    <button type = 'submit' name="accept" value={{join_req.user}}>Accept</button>
</form>
<br>
{% endfor %}

MEMBERS :
<br>
{% for member in members %}
<form method="POST">
    {% csrf_token %}
    <a href="{% url 'pages:user' member.reg_no %}">{{member.first_name}} - {{member.reg_no}}</a>
    <button type = 'submit' name="remove" value={{member.reg_no}}>Remove</button>
    {% if member in mods %}
        <button type = 'submit' name="removemod" value={{member.reg_no}}>Unmodify</button>
    {% else %}
        <button type = 'submit' name="makemod" value={{member.reg_no}}>Modify</button>
    {% endif %}
</form>
<br>
{% endfor %}

templates/request.html
{% if not req %}
    <form method="post">
        {% csrf_token %}
        <button name="request" value={{request.user}}>Request to join</button>
    </form>
{% else %}
    Requested.
{% endif %}

templates/test.html

<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
        
    </head>
    <body>
      <div id="carouselExample" class="carousel slide">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="/media/Dragonfruit.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>First slide label</h5>
                <p>Some representative placeholder content for the first slide.</p>
              </div>
          </div>
          <div class="carousel-item">
            <img src="/media/DragonfruitCurd.jpg" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="/media/Croissant(Yum).jpg" class="d-block w-100" alt="...">
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>

  <script>
    $(document).ready(function() {
      $('.carousel').carousel();
    });
  </script>
</body>
</html>

templates/user.html

<html>
    <head>
        <title>{{user.first_name}}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
        <style>
            body{
                background-color: lightblue;
            }
            .col-md-4{
                background-image: linear-gradient(to right, aqua, blue);
                width:fit-content
            }
            h2{
                color: blueviolet;
            }
            .col{
                background-color: aquamarine;
            }
            input{
                width:95%;
                font-family:'Courier New', Courier, monospace;
                font-size:x-large;
                margin:1%;
                border-radius: 0%;
                height:10%;
            }
            label{
                font-size: xx-large;
            }
            button{
                background-color: blue;
                border-radius: 10%;
            }
            
        </style>
    </head>
    <body>
        <div class = 'container p-5 my-5 bg-dark text-light'>
            <h1>Your Profile</h1>
        </div>
        <div class = 'row'>
            <center>
            <div class = 'col-lg-4'>
                <div class = 'card mb-4'>
                    <div class = 'row'>
                        <div class = 'col-md-4'>
                            <div class = 'card-body text-center'>
                                <img src = "{{ user.pic.url }}" alt = 'avatar' class = 'rounded-circle img-fluid my-4' style = "width:150px">
                                <h1>{{user.first_name}}<br></h1>
                            </div>
                        </div>
                        <div class = 'col'>
                            <div class = 'card-body text-center'>
                        
                                <h2>Registration No:</h2> <h3>{{user.reg_no}}</h3><br>
                                <h2>Staff Status: </h2>
                                <h3>{{user.is_staff}}</h3>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </center>
        </div>

        <div class = 'container p-3 my-4 bg-dark text-light'>
            <h1>Edit Profile: </h1>
        </div>
        <div class = 'formContainer'>
            <form method = 'POST' id = 'postForm'>
                {% csrf_token %}
                {{form.as_p}}
                <input type = 'text' id = 'password'>
                <input type = 'hidden' id = 'name' value = "{{user.first_name}}">
                <button type = 'submit'>Change</button>
            </form>

        </div>

    </body>

    <script>
        $(document).on('submit', '.formContainer form', function(e){
            e.preventDefault()
            var csrf = '{{csrf_token}}';
            var reqName = $("#name").val();
            $.ajax({
                type: 'POST',
                url: '/user/'+reqName,
                data: {
                    newPass: $("#password").val(),
                    csrfmiddlewaretoken: csrf
                }
            })
            $("#password").val('');
        })
    </script>
</html>